#include "../sigroam.h"

#include <sigroam_icons.h> /* I_sr1g_qr -- generated by fbt from the png in assets, see application.fam */

/*
 * The About page is a **retention slot, not an acquisition slot** (decided 2026-08-31).
 * Anyone who can read this page has already installed the app -- the acquisition
 * decision point is the Catalog `description` (where inline / automatic links are
 * explicitly allowed), and that is where the full pitch and links belong.
 * This page does only three things: state the version, make clear "this is not an
 * attack tool", and give the single outbound entry point.
 *
 * Three pieces of dead weight were removed by user decision; do not add them back:
 *  (1) The four rows of Bloom false-positive data -- developer verification numbers
 *      from T2.5 that users neither understand nor care about; moved to the README.
 *  (2) The always-visible Log Device / Log baud rows -- pure noise when there is no
 *      conflict, and when there IS a real conflict the CONFLICT branch below surfaces
 *      by itself (conditional display = zero noise).
 *  (3) The item-by-item list of seven attack techniques -- compressed into one positive
 *      statement (saying what it does is both shorter and more credible than enumerating
 *      what it does not do).
 *
 * NOTE: the compliance statement itself **must not be removed**: wardriving-class apps
 *    draw reviewer suspicion by nature, and official clause 4 explicitly forbids
 *    encouraging illegal activity -- this paragraph is a protective asset, not politeness.
 *
 * [2026-09-01 T4.14] Added the QR code; the layout became two regions of text_box plus an
 * icon. Three consequences -- read before editing:
 *  (1) **There is no scrolling any more.** The original widget_add_text_scroll_element is a
 *      fullscreen element and would overlap the icon, so it was replaced with two
 *      area-bounded text_boxes. The cost: the copy must fit one screen, and anything
 *      beyond it is simply clipped away.
 *  (2) **`\e#` bold and `\ec` centering are no longer used.** The centering witnessed on
 *      hardware in T4.13 is gone; this is a deliberate trade -- within a budget of 6 rows
 *      and 102 characters, centering is not worth a whole row.
 *      (text_box itself still supports `\e#`, so a bold heading can be added later.)
 *  (3) **The conflict state uses a degraded layout**: a Log Device conflict adds 4 rows,
 *      which the two regions cannot hold -- so it falls back to the fullscreen text_scroll
 *      and **draws no code**, guaranteeing the conflict notice stays complete and scrollable.
 *      The predicate is sigroam_log_device_conflicts(), the same function as before.
 *
 * Layout (coordinates computed: SR_VIEW_COLS=20 -> 6.4 px/char; the 37x37 code already
 * includes a 4-module quiet zone on each side):
 *
 *   x: 0                        90 91              127
 *      ┌─────────────────────────┬──────────────────┐
 *  b10 │ SigRoam <ver>           │ I_sr1g_qr        │
 *  b20 │ Wardriving              │ 37x37 (x=91,y=0) │
 *  b30 │ Receive-only.           │ QR spans y=0..36 │
 *  b40 │ No attack.              │ (b40 clears by x)│
 *      ├─────────────────────────┴──────────────────┤
 *  b50 │ Marauder compatible    (full width, <=20)  │
 *  b60 │ go.pingequa.com/sr1g                       │
 *      └────────────────────────────────────────────┘
 *
 * Two INDEPENDENT clearances -- do not conflate them:
 *    (1) The four upper rows clear the code by **x** -- their width must be <= 91 px
 *        (the longest, "Receive-only." at 13 chars, is about 83 px).
 *        String elements are **not clipped**: anything wider is drawn straight over the
 *        code. The cap height of b40 at 30 is still inside the code's y range, so it is
 *        safe **only because** x is bounded, not because of y.
 *    (2) The full-width rows clear the code by **y** -- baseline >= 47
 *        (cap height = baseline - ascent >= 37).
 *        50 was chosen over 47 to keep a full font_height (about 10) away from the last
 *        upper row's baseline of 40, so the rows do not collide.
 *        The last row, 60 + descent (about 2) = 62 < 64: flush with the bottom but inside.
 * The upper width of 91 is not arbitrary: 91 + 37 = 128 lands exactly on the right edge.
 *
 * [Revised 2026-09-01 after the B-stage rejection] The original used two
 * widget_add_text_box_element regions for layout, and **hardware photos showed the upper
 * and lower text overlapping** (rows 2 and 3 each carried two overlapping sentences, and
 * row 4 had only one left).
 * Root cause: the line advance in `elements_text_box` is
 * `line[i].y = line[i-1].y + leading_default`, and leading **falls back to leading_min when
 * the region height is insufficient** (official elements.c) -- the lower region was given
 * 64-37 = 27 px for 3 rows = 9 px per row, which is not enough, so it did not honestly
 * start at y=37.
 * More fundamentally, the geometry had skipped a step: the **cap height** of a full-width
 * row must not enter the code area -> the first baseline must be at least 47.
 *    NOTE: the conclusion drawn at the time, "only 3+2=5 rows fit", **overcounted by one
 *    step**: the fourth upper row (baseline 40) clears the code via x <= 91 and does not
 *    need to yield on y; and a lower first baseline of 50 still satisfies >= 47.
 *    So the real capacity is **4+2 = 6 rows**, and the 5-row plan is void.
 * It now uses widget_add_string_element and **gives each row its own baseline**, relying on
 * no automatic layout at all: the AlignBottom branch of `canvas_draw_str_aligned` **does not
 * adjust y** (read from the official canvas.c), so y IS the baseline -- the same coordinate
 * semantics as canvas_draw_str(x, baseline) in views/sr_view_dash.c.
 */

/* In the normal layout only the first row needs a version filled in at runtime; the other
 * four are static literals.
 * widget_add_string_element stores a FuriString copy internally (official
 * widget_element_string.c), so passing a literal or app->about_text is equally safe. */
static void sigroam_scene_about_fill_top(SigRoamApp* app) {
    snprintf(app->about_text, sizeof(app->about_text), "SigRoam %s", SR_FAP_VERSION);
}

/* Draw one row. y IS the baseline: the AlignBottom branch of canvas_draw_str_aligned does not adjust y. */
static void sigroam_scene_about_line(SigRoamApp* app, int32_t baseline, const char* text) {
    widget_add_string_element(
        app->widget, 0, baseline, AlignLeft, AlignBottom, FontSecondary, text);
}

/* Degraded layout (Log Device conflict): one fullscreen scrollable text block, with nothing
 * left out. The full three-sentence compliance statement and hardware note are kept here --
 * with no code drawn there is no space pressure, so there is no reason to trim along with it. */
static void sigroam_scene_about_fill_conflict(SigRoamApp* app) {
    snprintf(
        app->about_text,
        sizeof(app->about_text),
        "\e#SigRoam %s\n"
        "\n"
        "CONFLICT: set\n"
        "Settings > System >\n"
        "Log Device to Off\n"
        "\n"
        "Receive-only. No\n"
        "attack features.\n"
        "It only listens.\n"
        "\n"
        "Works with ESP32\n"
        "Marauder scanners\n"
        "such as Scout Lite.\n"
        "\n" SR_BRAND_URL "\n",
        SR_FAP_VERSION);
}

void sigroam_scene_about_on_enter(void* context) {
    SigRoamApp* app = context;

    widget_reset(app->widget);

    if(sigroam_log_device_conflicts()) {
        sigroam_scene_about_fill_conflict(app);
        /* Do not take the return of widget_add_text_box_element: Official is
         * void, Momentum is WidgetElement*. text_scroll is void on both. */
        widget_add_text_scroll_element(
            app->widget, 0, 0, SR_CANVAS_W, SR_CANVAS_H, app->about_text);
    } else {
        sigroam_scene_about_fill_top(app);

        /* Four upper rows: width must be <= SR_ABOUT_QR_X(91), about 14 chars, or they are
         * drawn over the code.
         * Row 4's baseline of 40 (cap height 30) is still inside the code's y range; it clears
         * by the x bound, not by y. */
        sigroam_scene_about_line(app, 10, app->about_text);
        sigroam_scene_about_line(app, 20, "Wardriving");
        sigroam_scene_about_line(app, 30, "Receive-only.");
        sigroam_scene_about_line(app, 40, "No attack.");

        /* Two lower rows: full width. The baseline must be >= 47 to stay out of the code's
         * quiet zone (cap height = baseline - ascent).
         * 50/60 rather than 47/57: a full font_height (about 10) away from the last upper
         * row's baseline of 40, avoiding collision.
         *
         * NOTE: "Marauder compatible" is a **compatibility statement, not an identity**
         *    (user decision, 2026-09-01): SigRoam is dedicated wardriving software that is
         *    compatible with Marauder, not something "made for Marauder".
         *    The in-house firmware in ADR-023 speaks the @SR1 protocol -- hardcoding Marauder
         *    would block that path.
         *    An earlier version read "For ESP32 Marauder", which drifted toward exclusivity
         *    and was rejected.
         *
         * The last row and the QR code resolve to the same short link -- the code encodes
         * "https://" SR_BRAND_URL, so changing SR_BRAND_URL requires regenerating
         * assets/sr1g_qr.png as well (see constraint (2) in sigroam.h). */
        sigroam_scene_about_line(app, 50, "Marauder compatible");
        sigroam_scene_about_line(app, 60, SR_BRAND_URL);

        widget_add_icon_element(app->widget, SR_ABOUT_QR_X, 0, &I_sr1g_qr);
    }

    view_dispatcher_switch_to_view(app->view_dispatcher, SigRoamViewWidget);
}

bool sigroam_scene_about_on_event(void* context, SceneManagerEvent event) {
    UNUSED(context);
    UNUSED(event);
    /* Back not consumed → scene_manager pops to Start. */
    return false;
}

void sigroam_scene_about_on_exit(void* context) {
    SigRoamApp* app = context;
    widget_reset(app->widget);
}
